server:
  http_port: 8080
  grpc_port: 9090
  environment: development
  version: "1.0.0"
  domain: localhost
  tls_enabled: false

database:
  host: localhost
  port: 3306
  username: mynodecp
  password: mynodecp
  database: mynodecp
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 5m
  ssl_mode: disable

redis:
  host: localhost
  port: 6379
  password: ""
  database: 0
  pool_size: 10
  min_idle_conns: 2
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s

auth:
  jwt_secret: "your-super-secret-jwt-key-change-this-in-production"
  jwt_expiration: 15m
  refresh_expiration: 7d
  password_min_length: 8
  password_require_upper: true
  password_require_lower: true
  password_require_digit: true
  password_require_special: true
  two_factor_enabled: true
  session_timeout: 24h

security:
  rate_limit_enabled: true
  rate_limit_requests: 100
  rate_limit_window: 1m
  cors_enabled: true
  cors_allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
  csrf_enabled: true
  hsts_enabled: true
  hsts_max_age: 31536000
  content_type_nosniff: true
  x_frame_options: "DENY"
  xss_protection: true

logging:
  level: info
  format: json
  output: stdout
  max_size: 100
  max_backups: 3
  max_age: 28
  compress: true
